Vagrant.configure("2") do |config|
  # Enable and configure hostmanager plugin
  config.hostmanager.enabled = true
  config.hostmanager.manage_host = true
  config.vbguest.auto_update = false if Vagrant.has_plugin?('vagrant-vbguest')
  
  ### DB VM ###
  config.vm.define "db01" do |db01|
    db01.vm.box = "almalinux/9"
    db01.vm.hostname = "db01"
    db01.vm.network "private_network", ip: "192.168.56.25"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end

  ### Memcached VM ###
  config.vm.define "mc01" do |mc01|
    mc01.vm.box = "almalinux/9"
    mc01.vm.hostname = "mc01"
    mc01.vm.network "private_network", ip: "192.168.56.26"
    mc01.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end

  ### RabbitMQ VM ###
  config.vm.define "rmq01" do |rmq01|
    rmq01.vm.box = "eurolinux-vagrant/centos-stream-9"
    rmq01.vm.hostname = "rmq01" # Corrected hostname
    rmq01.vm.network "private_network", ip: "192.168.56.27"
    rmq01.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end

  ### app01 VM ###
  config.vm.define "app01" do |app01|
    app01.vm.box = "almalinux/9"
    app01.vm.hostname = "app01"
    app01.vm.network "private_network", ip: "192.168.56.28"
    app01.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end

  ### web01 VM ###
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.hostname = "web01"
    web01.vm.network "private_network", ip: "192.168.56.29"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end
end
