# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Define first virtual machine
  config.vm.define "web01" do |web01|
    web01.vm.box = "ubuntu/jammy64"
    web01.vm.network "private_network", ip: "192.168.56.41"
    web01.vm.hostname = "web01"
    web01.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end
 
  # Define second virtual machine
  config.vm.define "web02" do |web02|
    web02.vm.box = "ubuntu/jammy64"
    web02.vm.network "private_network", ip: "192.168.56.42"
    web02.vm.hostname = "web02"
    web02.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end
  
  # Define third virtual machine
  config.vm.define "web03" do |web03|
    web03.vm.box = "ubuntu/jammy64"
    web03.vm.network "private_network", ip: "192.168.56.43"
    web03.vm.hostname = "web03"
    web03.vm.provider "virtualbox" do |vb|
      vb.memory = "1600"
      vb.cpus = "3"
    end
  end

  # Define second virtual machine
  config.vm.define "db01" do |db01|
    db01.vm.box = "centos/8"
    db01.vm.network "private_network", ip: "192.168.56.44"
    db01.vm.hostname = "db01"
    db01.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = "3"
    end
    # additional provisioning for db01
    db01.vm.provision "shell", inline: <<-SHELL
      sudo yum install -y mariadb-server
      sudo systemctl start mariadb
      sudo systemctl enable mariadb
    SHELL

  end

end
